accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup



urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', signup, name='signup')
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='home')),
    path("admin/", admin.site.urls),
    path('receipts/', include('receipts.urls')),
    path('accounts/', include('accounts.urls')),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name='home'),
    path('create/', ReceiptCreateView.as_view(), name='create_receipt'),
    path('categories/', ExpenseCategoryListView.as_view(), name='list_categories'),
    path('accounts/', AccountListView.as_view(), name='accounts'),
    path('categories/create/', ExpenseCategoryCreateView.as_view(), name='create_category' ),
    path('accounts/create/', AccountCreateView.as_view(), name='create_account'),

]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name='categories', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, related_name='accounts', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(auto_now_add=False)
    purchaser = models.ForeignKey(USER_MODEL, related_name="receipts", on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, related_name='receipts', on_delete=models.CASCADE)
    account = models.ForeignKey(Account, related_name='receipts', on_delete=models.CASCADE, null=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


from receipts.models import Receipt, ExpenseCategory, Account

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = 'receipts/list.html'

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = 'receipts/create.html'
    fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']

    def get_form(self, *args, **kwargs):
        form = super(ReceiptCreateView, self).get_form(*args, **kwargs)
        form.fields['category'].queryset = ExpenseCategory.objects.filter(owner=self.request.user)
        form.fields['account'].queryset = Account.objects.filter(owner=self.request.user)
        return form

    def form_valid(self,form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = 'receipts/categories.html'

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = 'receipts/accounts.html'

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = 'receipts/categorycreate.html'
    fields = ['name']

    def form_valid(self, form):
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect('list_categories')


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = 'receipts/accountcreate.html'
    fields = ['name', 'number']

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect('accounts')

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expenses</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'home' %}">Receipts</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
          </li>
          <li>
            <a href="{% url 'accounts' %}">Accounts</a>
          </li>
          <li>
            <a href="{% url "logout" %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url "signup" %}">Sign Up</a>
          </li>
          <li>
            <a href="{% url "login" %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    {% block content %}{% endblock content %}
  </body>
</html>

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expenses</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'home' %}">Receipts</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
          </li>
          <li>
            <a href="{% url 'accounts' %}">Accounts</a>
          </li>
          <li>
            <a href="{% url "logout" %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url "signup" %}">Sign Up</a>
          </li>
          <li>
            <a href="{% url "login" %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    {% block content %} {% endblock content %}
  </body>
</html>

receipts/templates/receipts/accountcreate.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>

{% endblock content %}

receipts/templates/receipts/accounts.html
{% extends 'base.html' %} {% block content %}

<main>
  <h1>My Accounts</h1>
  <div>
    <ul>
      <a href="{% url 'create_account' %}">Create an Account</a>
    </ul>
  </div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Number of Receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for account in account_list %}
      <tr>
        <td>{{account}}</td>
        <td>{{account.number}}</td>
        <td>{{account.receipts.all | length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/categories.html
{% extends 'base.html' %} {% block content %}

<main>
  <h1>My Categories</h1>
  <div>
    <ul>
      <a href="{% url 'create_category' %}">Create a Category</a>
    </ul>
  </div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of Receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for category in expensecategory_list %}
      <tr>
        <td>{{category}}</td>
        <td>{{category.receipts.all | length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/categorycreate.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Create Category</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>

{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %}

<main>
  <h1>My Receipts</h1>
  <div>
    <ul>
      <a href="{% url 'create_receipt' %}">Create a Receipt</a>
    </ul>
  </div>
  <table>
    <thead>
      <tr>
        <th>Vendor</th>
        <th>Total</th>
        <th>Tax</th>
        <th>Date</th>
        <th>Category</th>
        <th>Account</th>
      </tr>
    </thead>
    <tbody>
      {% for receipt in receipt_list %}
      <tr>
        <td>{{receipt.vendor}}</td>
        <td>{{receipt.total}}</td>
        <td>{{receipt.tax}}</td>
        <td>{{receipt.date |date:"m-d-Y"}}</td>
        <td>{{receipt.category}}</td>
        <td>{{receipt.account}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}